### ISSUE TITLE
Optional values do not work anymore

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [whitequark/ppx_deriving_yojson#28]
Hi,

I have an API that may or may not include some keys, so I used "option" types to mark the result as optional. I believe this used to work, but the code complains about optional values (I'm using version 2.2):

```ocaml
type f = { exist: int; may: int option; } [@@deriving of_yojson]
f_of_yojson (Yojson.Safe.from_string "{\"exist\": 10}")
```

Which yields <code>- : [> \`Error of bytes | \`Ok of f ] = \`Error "f.may"</code>. When adding the `"may"` key, it parses it correctly.

**Comment by whitequark** [comment]
Nope, never worked. See the docs: `option	Null or 'a`.

You may take a look at `[@@deriving yojson { strict=false }]`.

**Comment by Leonidas-from-XIV** [comment]
But with `strict = false` and leaving out the key from the struct I can't access the value even if it does exist.

**Comment by whitequark** [comment]
Wait, no, I screwed up. `[@default None]` is what you need here.

**Comment by Leonidas-from-XIV** [comment]
You are right, that works for me just fine. Thanks!
