### ISSUE TITLE
Type name `t` yields strange constructor function names

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [whitequark/ppx_deriving_yojson#29]
When the type is named `t`, the prefix is omitted:

```
type t = { has_2fa: bool; } [@@deriving of_yojson];;
type t = { has_2fa: bool; }
val of_yojson : Yojson.Safe.json -> [> `Error of bytes | `Ok of t ] = <fun>
```

OTOH, with a different name:
```
type f = { has_2fa: bool; } [@@deriving of_yojson];;
type f = { has_2fa : bool; }
val f_of_yojson : Yojson.Safe.json -> [> `Error of bytes | `Ok of f ] = <fun>
```

I'm not sure this is a bug, since it clearly targets the `Module.t` case, but maybe it could be somehow restricted. Or maybe just documented, since this looks useful, but is not mentioned in the readme.

**Comment by whitequark** [comment]
Yeah, documentation would be nice.
