### ISSUE TITLE
[@default None] in yojson vs create

### ISSUE THREAD

**Issue by hcarty** [whitequark/ppx_deriving_yojson#34]
```ocaml
type t = {
  x : int;
  y : (int option [@default None]);
} [@@deriving create, yojson]
```
gives:
```ocaml
type t = { x : int; y : int option; }
val create : x:int -> ?y:int option -> unit -> t
val to_yojson : t -> Yojson.Safe.json
val of_yojson : Yojson.Safe.json -> [ `Error of string | `Ok of t ]
```
`[@default None]` is potentially beneficial for `yojson` because it allows for a missing `y` on input and output.  Unfortunately it causes `create` to generate a `?y:int option` parameter rather than `?y:int`.

Is there a way to work around this?

**Comment by whitequark** [comment]
Try replacing `typ` with `{ typ with ptyp_attributes = [] }` here: https://github.com/whitequark/ppx_deriving_yojson/blob/master/src/ppx_deriving_yojson.ml#L45

**Comment by hcarty** [comment]
No change on a OCaml 4.02.3 snapshot - I still get the same `?y:int option`.

**Comment by hcarty** [comment]
Bah, I'm a fool.  I can use `[@yojson.default None]` so that the default only applies to the Yojson deriver.  Apologies for the noise.
