### ISSUE TITLE
Custom de/serializers for datatypes

### ISSUE THREAD

**Issue by spencerwi** [whitequark/ppx_deriving_yojson#42]
Given a JSON object like this:

```
{
    "username": "foo",
    "signupDate": "2016-01-01T23:00:00Z"
}
```

It would be nice to be able to represent this with a datatype:

```ocaml
type user = {
    username: string;
    signupDate: Core.Time.t [@fromjson core_time_of_yojson] [@tojson core_time_to_yojson];
} [@@deriving yojson]
```

where `core_time_of_yojson` is some method that converts Yojson's string representation of the `signupDate` json field to a `Core.Time.t`, and `core_time_to_yojson` is a similar method working the other direction.

**Comment by rgrinberg** [comment]
Why don't you just wrap `Core.Time.t`?

```ocaml
module My_core = struct
  type t = Core.Time.t
  let of_json json = ...
  let to_json t = ...
end
```

and use `My_core.t` in your json types.

**Comment by spencerwi** [comment]
That would work great! Sorry -- I'm kinda new to the OCaml world and wasn't sure such a thing could be done.

**Comment by rgrinberg** [comment]
No problem. This is a general ppx_deriving trick btw. It will work with any of the converters not just yojson.
