### ISSUE TITLE
4.03.0 support

### ISSUE THREAD

**Issue by hcarty** [whitequark/ppx_deriving_yojson#43]
The build fails when building under 4.03.0, both from opam and master.

**Comment by whitequark** [comment]
Ping me in about a week.

**Comment by Leonidas-from-XIV** [comment]
Ping :stuck_out_tongue_winking_eye:

**Comment by whitequark** [comment]
Wish granted. Note it doesn't handle record variants, that's a separate issue.

**Comment by hcarty** [comment]
Thanks!

**Comment by spencerwi** [comment]
Sorry if this is a dumb/rookie question, but is there a way to install this 4.03-compatible version via opam? I've tried `opam pin ppx_deriving_yojson https://github.com/whitequark/ppx_deriving_yojson.git#master`, but I still run into the same compile issue as prior to the fix (`The function applied to this argument has type ~?quoter:Ppx_deriving.quoter -> Parsetree.expression`).

**Comment by whitequark** [comment]
@spencerwi Nothing wrong with the question--currently this is somewhat broken as I haven't yet released a new ppx_deriving. So you need to pin both ppx_deriving and ppx_deriving_yojson.
