### ISSUE TITLE
Problem when deserialising large numbers

### ISSUE THREAD

**Issue by michipili** [whitequark/ppx_deriving_yojson#46]
When using **ppx_deriving** with **js_of_ocaml** I have a problem when deserialising not-too-small integers (with ten digits or more). The following code is a minimal example:

```
open Printf

type x = {
  a: int;
} [@@deriving yojson]

let json =  {json|{"a":9999999999}|json}

let () =
  eprintf
    "test_integer: %S: Back and forth.\n"
    (Yojson.Safe.(to_string(from_string json)))

let () =
  let x =
    x_of_yojson (Yojson.Safe.from_string json)
  in
  match x with
  | Result.Ok(actualx) -> eprintf "test_integer: %d\n" actualx.a
  | Result.Error(mesg) -> eprintf "test_integer: %s\n" mesg
```

The first test demonstrates that decoding and recoding json text using Yojson works, and especially that js_of_ocaml has no problem with the not-so-small integer constant.

~~~ console
node test_integer.js
test_integer: "{\"a\":9999999999}": Back and forth.
test_integer: Dynamodb_TestInteger.x.a
~~~ 

Replacing the integer type by int64 let the program run without errors:

~~~ console
test_integer: "{\"a\":9999999999}": Back and forth.
test_integer: 9999999999
~~~

Is there any special processing in `ppx_deriving` that could explain this discrepancy? Or is this more likely a `js_of_ocaml` bug? (The latter hypothesis seems to be ruled out by the first test.)

----

System information

~~~ console
opam list ppx_deriving ppx_deriving_yojson  yojson
# Available packages for 4.02.3:
ppx_deriving           4.0  Type-driven code generation for OCaml >=4.02
ppx_deriving_yojson    3.0  JSON codec generator for OCaml >=4.02
yojson               1.3.2  Yojson is an optimized parsing and printing library
~~~

**Comment by whitequark** [comment]
It is my understanding based on your report that this problem manifests exclusively on js_of_ocaml, and not natively. In this case this is a js_of_ocaml bug, that is not exposed for some reason when you write the deserialization code explicitly; OCaml does not (apart from the Obj module that I don't use) have a concept of "undefined behavior", so if it works on ocamlc, it ought to work the same way on js_of_ocaml *by definition* (of the OCaml language and standard library semantics).

Please reopen if you have a compelling counterargument, and I'll take a look.

**Comment by whitequark** [comment]
Incidentally, the code generated by ppx_deriving_yojson for your record basically consists of <code>match `Int x -> Result.Ok (x) >>= ...</code> with some fluff around it to handle the field name. ppx_deriving_yojson doesn't do any manipulation of the integer value whatsoever, that's all inside yojson. So I really don't see how it can be responsible here.
